# Generated by Django 4.1 on 2022-08-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='description',
            new_name='message',
        ),
    ]
